version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb
